version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: product-categories-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT:product-categories-service}
      MYSQL_DATABASE: product-categories-service-db
      MYSQL_USER: ${USERNAME:product-categories-service}
      MYSQL_PASSWORD: ${USERPASS:product-categories-service}
    ports:
      - "60050:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local