version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: products-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT:products-service}
      MYSQL_DATABASE: products-service-db
      MYSQL_USER: ${USERNAME:products-service}
      MYSQL_PASSWORD: ${USERPASS:products-service}
    ports:
      - "60060:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local