version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: recomendations-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT:recomendations-service}
      MYSQL_DATABASE: recomendations-service-db
      MYSQL_USER: ${USERNAME:recomendations-service}
      MYSQL_PASSWORD: ${USERPASS:recomendations-service}
    ports:
      - "60020:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local