version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: customers-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT:customers-service}
      MYSQL_DATABASE: customers-service-db
      MYSQL_USER: ${USERNAME:customers-service}
      MYSQL_PASSWORD: ${USERPASS:mypassword}
    ports:
      - "60010:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
