version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: shopping-cart-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT:shopping-cart-service}
      MYSQL_DATABASE: shopping-cart-service-db
      MYSQL_USER: ${USERNAME:shopping-cart-service}
      MYSQL_PASSWORD: ${USERPASS:shopping-cart-service}
    ports:
      - "60090:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local