version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: negative-feedback-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT:negative-feedback}
      MYSQL_DATABASE: negative-feedback-db
      MYSQL_USER: ${USERNAME:negative-feedback}
      MYSQL_PASSWORD: ${USERPASS:negative-feedback}
    ports:
      - "60020:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
