version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: user-activity-logs-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT:user-activity-logs-service}
      MYSQL_DATABASE: user-activity-logs-service-db
      MYSQL_USER: ${USERNAME:user-activity-logs-service}
      MYSQL_PASSWORD: ${USERPASS:user-activity-logs-service}
    ports:
      - "60100:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local