version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: reviews-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT:reviews-service}
      MYSQL_DATABASE: reviews-service-db
      MYSQL_USER: ${USERNAME:reviews-service}
      MYSQL_PASSWORD: ${USERPASS:reviews-service}
    ports:
      - "60080:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local